ALTER TABLE "Workspace"
ADD COLUMN "globalAccessPasswordHash" TEXT,
ADD COLUMN "globalAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "matchesAccessPasswordHash" TEXT,
ADD COLUMN "matchesAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "newMatchAccessPasswordHash" TEXT,
ADD COLUMN "newMatchAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "mapsAccessPasswordHash" TEXT,
ADD COLUMN "mapsAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "reportsAccessPasswordHash" TEXT,
ADD COLUMN "reportsAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "maintenanceAccessPasswordHash" TEXT,
ADD COLUMN "maintenanceAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "settingsAccessPasswordHash" TEXT,
ADD COLUMN "settingsAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "helpAccessPasswordHash" TEXT,
ADD COLUMN "helpAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "analysisAccessPasswordHash" TEXT,
ADD COLUMN "analysisAccessPasswordVersion" INTEGER NOT NULL DEFAULT 0;
